### ISSUE TITLE
CodeGlob Roadmap

### ISSUE THREAD

**Issue by hamdivazim** [hamdivazim/CodeGlob#4]
## CodeGlob Roadmap
Here is our plan to complete CodeGlob:
- [ ] Design (frontend)
  - [ ] Home Page (Done)
  - [ ] Profile Page (In progress)
  - [ ] Other pages
  - [ ] Docs
    - [ ] Home page (in progress)
    - [ ] Other pages

- [ ] Server (backend)
  - [ ] Use django authentication
  -  [

**Comment by hamdivazim** [comment]
Whoops, this is incomplete. I will submit a new issue with the roadmap.
