### ISSUE TITLE
CodeGlob Roadmap

### ISSUE THREAD

**Issue by hamdivazim** [hamdivazim/CodeGlob#5]
## CodeGlob Roadmap
Here is our plan to complete CodeGlob:
- [ ] Design (frontend)
  - [x] Home Page (Done)
  - [ ] Profile Page (Almost done)
  - [ ] Other pages
  - [ ] Docs
    - [ ] Home page (in progress)
    - [ ] Other pages

- [ ] Server (backend)
  -  [ ] Use django authentication
  -  [ ] Use SQL to store data
  -  [ ] Get a domain
  -  [ ] Add website to domain server
  -  [ ] Make sure the backend can connect to the frontend templates

**Comment by MKM12345** [comment]
@OctoBoss1305
